### ISSUE TITLE
Competing a key binding with the Julia extention

### ISSUE THREAD

**Issue by nosuz** [kkangmj/markdown-code-block#1]
Thank you for releasing this very convenient extension.

But the key binding Alt + j for javascript code block competes with Julia's extension, 
julialang.language-julia. The extension has some Alt + j with the second key without 'when' conditions.

Do you have any idea to use Alt + j with the julia extension?

**Comment by kkangmj** [comment]
Hi, I'm glad to hear that code block markdown extension is convenient. I've checked Julia extension and how about changing your keyboard binding for js code block to something else? 

Because when a key(ex. Alt + J) is pressed, the rules are evaluated from bottom to top and the first rule that matches, both the key and in terms of when, is accepted. If you open keyboard shortcuts editor, commands are listed in alphabetical order. Julia extension is above Code Block extension so if there's duplicate, vscode will match with shortcuts of Julia extension.

To change keyboard binding, open keyboard shortcuts editor (File > Preferences > Keyboard Shortcuts in Windows, Code > Preferences > Keyboard Shortcuts on macOS). After opening editor, search commands you want to change, click it and press desired keyboard binding.
